// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/clientes": {
    params: {};
  };
  "/produtos": {
    params: {};
  };
  "/estoque": {
    params: {};
  };
  "/vendas": {
    params: {};
  };
  "/login": {
    params: {};
  };
  "/*": {
    params: {
      "*": string;
    };
  };
};

type RouteFiles = {
  "root.jsx": {
    id: "root";
    page: "/" | "/clientes" | "/produtos" | "/estoque" | "/vendas" | "/login" | "/*";
  };
  "routes/[clientes]._index.jsx": {
    id: "routes/[clientes]._index";
    page: "/clientes";
  };
  "routes/[produtos]._index.jsx": {
    id: "routes/[produtos]._index";
    page: "/produtos";
  };
  "routes/[estoque]._index.jsx": {
    id: "routes/[estoque]._index";
    page: "/estoque";
  };
  "routes/[vendas]._index.jsx": {
    id: "routes/[vendas]._index";
    page: "/vendas";
  };
  "routes/[login]._index.jsx": {
    id: "routes/[login]._index";
    page: "/login";
  };
  "routes/_index.jsx": {
    id: "routes/_index";
    page: "/";
  };
  "routes/[404]._index.jsx": {
    id: "routes/[404]._index";
    page: "/*";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.jsx");
  "routes/[clientes]._index": typeof import("./app/routes/[clientes]._index.jsx");
  "routes/[produtos]._index": typeof import("./app/routes/[produtos]._index.jsx");
  "routes/[estoque]._index": typeof import("./app/routes/[estoque]._index.jsx");
  "routes/[vendas]._index": typeof import("./app/routes/[vendas]._index.jsx");
  "routes/[login]._index": typeof import("./app/routes/[login]._index.jsx");
  "routes/_index": typeof import("./app/routes/_index.jsx");
  "routes/[404]._index": typeof import("./app/routes/[404]._index.jsx");
};